"""gRPC client for the Scorer — bounded concurrency, hard deadline, no retries on score.

Three choices here are deliberate and each has a cost if reversed:

* **A hard per-call deadline.** A score that arrives after the window it describes has been
  superseded is worse than no score: it would enter the k-of-n evidence sequence out of order. On
  timeout the window is dropped and the *stream* continues.
* **No retry on ``ScoreWindow``.** Retrying means the same audio is scored twice and could be counted
  twice in the evidence sequence, or arrive after a later window. Retry belongs to ``Health``, which
  is idempotent, not to scoring.
* **Bounded concurrency.** One GPU, one model instance (rules.md R-32). Unbounded in-flight requests
  would queue inside the Scorer where the Gateway cannot see the backpressure, and queued audio is
  retained audio (rules.md R-20). The semaphore makes the limit visible on the Gateway side, where
  the refuse-rather-than-queue decision is made.

gRPC never crosses the edge: inside the VPC on AWS, over the Compose network locally. mTLS between
Gateway and Scorer is a Phase-4 target — the five-day control is network isolation plus security
groups, and it must not be described as mTLS today (rules.md R-01).
"""

from __future__ import annotations

import asyncio
from dataclasses import dataclass
from typing import Final

import grpc

from app.constants import CONTRACT_ID, SAMPLE_RATE_HZ, WINDOW_BYTES
from app.telemetry.logging import get_logger

# Generated by scripts/gen_proto.sh from contracts/voice_scorer.proto. Committed, not built at
# runtime, so a stub/contract mismatch is caught in CI rather than at demo time.
from app.scorer import voice_scorer_pb2 as pb  # type: ignore[attr-defined]
from app.scorer import voice_scorer_pb2_grpc as pb_grpc  # type: ignore[attr-defined]

_log = get_logger(__name__)

#: Keepalive matters because the ALB and the Cloud Map path both sit between these processes; an
#: idle-reaped connection would otherwise surface as a failed score on the first window of a session.
_CHANNEL_OPTIONS: Final[list[tuple[str, int]]] = [
    ("grpc.keepalive_time_ms", 20_000),
    ("grpc.keepalive_timeout_ms", 5_000),
    ("grpc.keepalive_permit_without_calls", 1),
    ("grpc.max_send_message_length", 2 * 1024 * 1024),
    ("grpc.max_receive_message_length", 1 * 1024 * 1024),
    # Fail fast instead of buffering calls against a dead backend. A "waiting for ready" call would
    # hold a window in memory while the Scorer is down.
    ("grpc.enable_retries", 0),
]


class ScorerUnavailable(Exception):
    """The Scorer could not produce a score for this window. App code ``SCORER_UNAVAILABLE``."""

    __slots__ = ("code",)

    def __init__(self) -> None:
        super().__init__("SCORER_UNAVAILABLE")
        self.code = "SCORER_UNAVAILABLE"


@dataclass(frozen=True, slots=True)
class WindowScore:
    """One scored window, as the Gateway sees it.

    ``raw_score`` is carried for diagnostics and ONNX-parity checking only. The policy engine's
    input type (:class:`~app.policy.engine.WindowObservation`) has no field for it, so it cannot
    reach a decision by accident (rules.md R-11).
    """

    spoof_risk: float
    eligible: bool
    quality_flags: tuple[str, ...]
    model_version: str
    calibration_version: str
    detector_mode: str
    scorer_latency_us: int
    raw_score: float


@dataclass(frozen=True, slots=True)
class ScorerHealth:
    """Artifact identity from the Scorer. Half of the parity set (architecture.md section 5.1)."""

    ready: bool
    execution_provider: str
    model_version: str
    model_sha256: str
    calibration_version: str
    calibration_sha256: str
    detector_mode: str
    artifact_state: str
    contract_vector_parity_ok: bool


class ScorerClient:
    """Async gRPC client. One instance per process, created in the app lifespan."""

    __slots__ = ("_target", "_deadline_s", "_channel", "_stub", "_sem", "_max_concurrency", "_in_flight")

    def __init__(self, target: str, *, deadline_ms: int = 400, max_concurrency: int = 4):
        self._target = target
        self._deadline_s = deadline_ms / 1000.0
        self._max_concurrency = max_concurrency
        self._channel: grpc.aio.Channel | None = None
        self._stub: pb_grpc.VoiceScorerStub | None = None
        self._sem = asyncio.Semaphore(max_concurrency)
        self._in_flight = 0

    async def start(self) -> None:
        """Open the channel. Insecure by design — see the module docstring on transport scope."""
        self._channel = grpc.aio.insecure_channel(self._target, options=_CHANNEL_OPTIONS)
        self._stub = pb_grpc.VoiceScorerStub(self._channel)

    async def close(self) -> None:
        if self._channel is not None:
            await self._channel.close(grace=1.0)
            self._channel = None
            self._stub = None

    @property
    def in_flight(self) -> int:
        """Requests currently occupying a concurrency slot. Read by the backpressure decision."""
        return self._in_flight

    @property
    def saturated(self) -> bool:
        return self._in_flight >= self._max_concurrency

    async def score_window(self, *, pcm_window: bytes, window_seq: int, session_ref: str) -> WindowScore:
        """Score exactly one 2.56 s window.

        ``session_ref`` MUST already be the HMAC pseudonym. There is no code path that would produce
        a raw reference here, and the assertion below exists so that if one is ever introduced it
        fails immediately rather than shipping the raw value across the wire (rules.md R-16).

        Raises:
            ScorerUnavailable: on deadline, unavailability, or any gRPC error. The caller drops the
                window and keeps the stream alive; it does not retry.
        """
        if self._stub is None:
            raise ScorerUnavailable()
        if len(pcm_window) != WINDOW_BYTES:
            # Never padded or trimmed to fit (rules.md R-24).
            raise ValueError(f"expected {WINDOW_BYTES} bytes, got {len(pcm_window)}")

        request = pb.ScoreWindowRequest(
            pcm_window=pcm_window,
            contract_id=CONTRACT_ID,
            sample_rate_hz=SAMPLE_RATE_HZ,
            window_seq=window_seq,
            session_ref=session_ref,
        )

        async with self._sem:
            self._in_flight += 1
            try:
                response = await self._stub.ScoreWindow(request, timeout=self._deadline_s)
            except grpc.aio.AioRpcError as exc:
                _log.warning(
                    "score_window failed",
                    extra={"window_seq": window_seq, "code": exc.code().name},
                )
                raise ScorerUnavailable() from exc
            finally:
                self._in_flight -= 1

        return WindowScore(
            spoof_risk=float(response.spoof_risk),
            eligible=bool(response.eligible),
            quality_flags=tuple(pb.QualityFlag.Name(f) for f in response.quality_flags),
            model_version=response.model_version,
            calibration_version=response.calibration_version,
            detector_mode=pb.DetectorMode.Name(response.detector_mode),
            scorer_latency_us=int(response.scorer_latency_us),
            raw_score=float(response.raw_score),
        )

    async def health(self, *, timeout_s: float = 2.0) -> ScorerHealth:
        """Read artifact identity. Idempotent, so this one is safe to retry."""
        if self._stub is None:
            raise ScorerUnavailable()
        try:
            response = await self._stub.Health(pb.HealthRequest(), timeout=timeout_s)
        except grpc.aio.AioRpcError as exc:
            raise ScorerUnavailable() from exc

        return ScorerHealth(
            ready=bool(response.ready),
            execution_provider=response.execution_provider,
            model_version=response.model_version,
            model_sha256=response.model_sha256,
            calibration_version=response.calibration_version,
            calibration_sha256=response.calibration_sha256,
            detector_mode=pb.DetectorMode.Name(response.detector_mode),
            artifact_state=response.artifact_state,
            contract_vector_parity_ok=bool(response.contract_vector_parity_ok),
        )
